services:
  db:
    image: postgres:15-alpine
    container_name: university-db
    environment:
      POSTGRES_DB: acme_university
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d acme_university"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: acme-university
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/acme_university"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin1234"
    ports:
      - "8080:8080"
    restart: always
volumes:
  db_data: